name: Publish uptimekuma docker image

# Controls when the workflow will run
on:
  # Trigger the workflow on push
  # but only for the master branch
  push:
    branches:
      - main
      
  # runs once every month
  schedule:
    - cron: "0 3 1 * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push uptimekuma docker images to GitHub Packages
    runs-on: ubuntu-latest
    
    steps:
      - 
        name: Check out the repo
        uses: actions/checkout@v4
      -
        name: Deploy to swarm
        uses: wshihadeh/docker-deployment-action@v2
        with:
          remote_docker_host: worker@levell.ch
          ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
          deployment_mode: docker-swarm
          copy_stack_file: true
          pull_images_first: true
          deploy_path: /home/worker/levell/uptimekuma
          stack_file_name: docker-compose.prod.yml
          keep_files: 2
          args: --with-registry-auth --prune uptimekuma